### ISSUE TITLE
Minor bugs in Custom Groups UI

### ISSUE THREAD

**Issue by dpakach** [owncloud/customgroups#217] opened 2019-05-02 08:16 UTC
### steps to reproduce
- Enter a character (invalid group name) in create group input but do not create.
- Try to rename a existing group with valid user name.

### exptected behavior
- group gets renamed correctly.

### Actual behavior
- Group gets renamed but the user gets a notification saying `The group name can not be empty or start with space. The group name should at least have 2 characters`.

### steps to reproduce
- Create a custom group.
- Try to change your role from group_owner to member.

### Exptected behavior
- The admin cannot change his role, a notification is displayed.

### Actual behavior
- The admin cannot change his role, a notification is displayed. and a loading icon appears next to user role and does not disappears until page reload.

**Comment by dpakach** [comment] 2019-05-02 08:27
![sr1](https://user-images.githubusercontent.com/19869344/57063829-3cce3100-6ce4-11e9-9745-d96787959691.gif)

**Comment by dpakach** [comment] 2019-05-02 08:27
![sr2](https://user-images.githubusercontent.com/19869344/57063836-46579900-6ce4-11e9-9280-500f424c83e6.gif)

**Comment by dpakach** [comment] 2019-05-02 08:48
These issues were present in last release too. so not regression.

**Comment by sharidas** [comment] 2019-05-02 09:18
Regarding change role issue raised:
If my understanding is correct:
- At least one of the user in a group should be a group owner ( by design ). So before we change the group role of `Group owner`, make sure we have another user as `Group owner`.
I have verified the same with one of our version 10.0.3 version. Hence I believe its by design.

**Comment by sharidas** [comment] 2019-05-02 09:38
Regarding `Renaming a group gives invalid notification even if the group name is valid.` issue raised:

I am not able to reproduce the same with customgroups version `0.4.0` ( master branch ) and core ( 10.2.0 git ). Here is the screen share: 
![customgroups](https://user-images.githubusercontent.com/3600427/57067159-d0efc680-6ceb-11e9-8185-1ef641766688.gif)

I have done this test on a scratch installation.

**Comment by dpakach** [comment] 2019-05-02 09:50
@sharidas try changing the name while renaming.

**Comment by dpakach** [comment] 2019-05-02 09:52
@sharidas regarding changing the role, the app behavior is correct, there should be at least one admin in the group but the loading icon next to the role keeps on showing after the error notification is displayed.

**Comment by sharidas** [comment] 2019-05-02 10:19
When user press enter key the whole page gets loaded and that's the reason if the create group tab as single character or invalid character to create group causes the notification to display. Say if the user has invalid character in the create group and user clicks the existing group name ( for rename ) and then renames the group and clicks the mouse in the plane area of the web page, then:
- [x] Group is renamed
- [x] No notification for the invalid group name is not shown.

**Comment by individual-it** [comment] 2019-05-06 03:47
@sharidas @dpakach can we close this?

**Comment by sharidas** [comment] 2019-05-06 05:14
@individual-it imho yes we can.

**Closed** 2019-05-06 05:27 UTC
Labels: QA, bug
