### ISSUE TITLE
After group creation and refresh role shows as 'member'

### ISSUE THREAD

**Issue by tomneedham** [owncloud/customgroups#75] opened 2017-06-27 12:03 UTC
1. Create a custom group
2. See if says role: group admin
3. Refresh the page
4. See it says role: member
5. Click on group
6. See on the sidebar it says role: group admin

**Comment by PVince81** [comment] 2017-06-27 12:14
Duplicate of https://github.com/owncloud/customgroups/issues/66.

Please review the matching PR

**Closed by PVince81** 2017-06-27 12:14 UTC
Labels: bug
